### ISSUE TITLE
updates for the docker image

### ISSUE THREAD

**Issue by ghost** [sdesbure/alpine_domoticz#1]
hi,
i am using your docker image, it seems to work well except domoticz shows ther eis an update which it will not install, how can it be updated ?
it complained of no wget and no sudo both of which i installed into the container but it still fails with 

domoticz.sh: unrecognized service
Failed to get D-Bus connection: Unknown error -1
please standby... (waiting 15 seconds)
domoticz.sh: unrecognized service
Failed to get D-Bus connection: Unknown error -1
2016-04-28 08:53:04.078  Error: Error executing script command (/src/domoticz/scripts/update_domoticz /src/domoticz/). returned: 256

**Comment by sdesbure** [comment]
Hello,
Yes I've seen that and yes it's annoying. What's weird is that I'm using the git repo of domoticz and so we should be at the last version!
I'll post an issue on domoticz to see why.

**Comment by sdesbure** [comment]
Well, I've resolved the issue: Domoticz takes its value from the size of git log... I was taking only the last part so that's why I had the default value. Now we're good :)

**Comment by ghost** [comment]
thanks, i am now on Version 3.4834 (March 2nd 2016)
