### ISSUE TITLE
disk I/O error

### ISSUE THREAD

**Issue by fdrijver** [sdesbure/alpine_domoticz#2]
Hi there,

I mapped a volume from my host filesystem to the container via the -v option. First boot it's creating the domoticz.db fine, but subsequent boots give a "disk I/O error" (for instance: 2016-06-15 14:05:00.276  Error: SQL Query("SELECT ID,Type,SubType,nValue,sValue,LastUpdate FROM DeviceStatus WHERE (Type=87)") : disk I/O error)

The db file is also not updating (timestamp wise). 
Am I doing something wrong?

Thanks

**Comment by sdesbure** [comment]
Hi, Well this is weird because I use the same way to work. By any chance, the user / group of the folder is the right one?

**Comment by fdrijver** [comment]
Well, that depends on what is the 'right' one 😃
It has my host username as owner. 'staff' as group (that's the root group on OS X). I tried a variety of permissions, including 777 on the whole lot. I also tried to user owner root, but all to no avail

**Comment by sdesbure** [comment]
Yeah I know for the right one (that's the reason I didn't put specifically one sorry ;) )
And how to you stop the container? via docker stop? (sorry if my questions are dumb but I try to figure out...)

**Comment by fdrijver** [comment]
Sorry for the late reply. Had all kinds of problems with my docker install.
Unfortunately Docker for Mac (which supposedly fixes volume sharing) doesn't work on my somewhat older Mac mini, so I decided to move everything out of docker.
Thanks for the help though!

**Comment by sdesbure** [comment]
ok sorry!
