### ISSUE TITLE
more errors updating

### ISSUE THREAD

**Issue by ghost** [sdesbure/alpine_domoticz#3]
Hello, i am now getting an update message in domoticz about version (beta) 5276, current 3.5231
if i press the update button it doesnt update, how do i update to the current version ?

do i need to recreate the docker image ?

**Comment by sdesbure** [comment]
Hello,
I've pushed a new version on the repo. Can you try with it (docker pul...) ?

**Comment by ghost** [comment]
seems to be updated to latest version now, will keep an eye on it for the next update, should it update from the GUI now ?

**Comment by sdesbure** [comment]
I don't take release of domoticz but I retrieve the last git version. Normally with updates from Debian I publish regularly new versions so I don't really need to rebuild manually but there were few Debian new docker images these last days. 
Being able to update inside a docker is a bit "breaking" docker philosophy.
