### ISSUE TITLE
stop logging to `/config` volume?

### ISSUE THREAD

**Issue by codekitchen** [sdesbure/alpine_domoticz#4]
Hi, thanks for the useful container. Right now, it's set up to log to both stdout and to `/config/domoticz.log`. I'd like to just use docker logging infrastructure, so I've modified my entrypoint so that it no longer logs to `/config`:

```Dockerfile
ENTRYPOINT ["/src/domoticz/domoticz", "-dbase", "/config/domoticz.db"]
```

Is that something you're interested in merging in?

**Comment by sdesbure** [comment]
Hello, thanks for the input. When I did this part, it was one of my first docker image so it's far from perfect :)
Ok, send me a pull request and I'll merge it !
thank you!

**Comment by codekitchen** [comment]
Cool, done in https://github.com/sdesbure/docker_domoticz/pull/5
