### ISSUE TITLE
Timezone not honored

### ISSUE THREAD

**Issue by rhaamo** [sdesbure/alpine_domoticz#8]
I tried to use the mount bind for timezone but it didn't worked.

I found that doing inside the docker container:

```
apk update
apk add tzdata
```

resolved the issue and after restarting, the correct TZ is used.

Maybe you need to add ```tzdata``` to Dockerfile.

**Comment by rhaamo** [comment]
I recreated the container with latest image and used only the env var TZ (no volume mount for /etc/localtime) and it seems ok !

Thanks for quick fix !

**Comment by sdesbure** [comment]
no problem :)
